# Generated by Django 3.1.4 on 2020-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('zodiac', models.PositiveSmallIntegerField(choices=[(1, 'Aries'), (2, 'Taurus'), (3, 'Gemini'), (4, 'Cancer'), (5, 'Leo'), (6, 'Virgo'), (7, 'Libra'), (8, 'Scorpio'), (9, 'Sagittarius'), (10, 'Capricorn'), (11, 'Aquarius'), (12, 'Pisces')], unique_for_date='date', verbose_name='Zodiac')),
                ('horoscope', models.TextField(verbose_name='Horoscope')),
            ],
        ),
    ]
